//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotVVM.Contrib.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CookieTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CookieTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotVVM.Contrib.Resources.CookieTexts", typeof(CookieTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always allowed.
        /// </summary>
        public static string AlwaysAllowed {
            get {
                return ResourceManager.GetString("AlwaysAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow all cookies.
        /// </summary>
        public static string Btn_AcceptAll {
            get {
                return ResourceManager.GetString("Btn_AcceptAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit options.
        /// </summary>
        public static string Btn_MoreOptions {
            get {
                return ResourceManager.GetString("Btn_MoreOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and close.
        /// </summary>
        public static string Btn_SaveAndClose {
            get {
                return ResourceManager.GetString("Btn_SaveAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We use cookies to analyze our traffic, personalize content and ads, and to provide some social media features. We also share information about your use of our site with our social media, advertising and analytics partners who may combine it with other information that you&apos;ve provided to them or that they&apos;ve collected from your use of their services..
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose which cookies you want to enable.
        /// </summary>
        public static string Dialog_Subtitle {
            get {
                return ResourceManager.GetString("Dialog_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necessary only.
        /// </summary>
        public static string OnlyNecessaryLink {
            get {
                return ResourceManager.GetString("OnlyNecessaryLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We use these cookies to measure, collect, analyse and report how users interact with our sites to better understand their behavior. Thanks to this, we can improve the site and provide better experience. The analytics service is provided by Google Inc..
        /// </summary>
        public static string Rule_Analytics {
            get {
                return ResourceManager.GetString("Rule_Analytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We use these cookies to measure conversions from our advertisement and banners distributed via Facebook. This allows us to better target the ads and make them more relevant to you..
        /// </summary>
        public static string Rule_FacebookPixel {
            get {
                return ResourceManager.GetString("Rule_FacebookPixel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We use these cookies to measure conversions from our advertisement and banners distributed via Google Ads. This allows us to better target the ads and make them more relevant to you..
        /// </summary>
        public static string Rule_GoogleAds {
            get {
                return ResourceManager.GetString("Rule_GoogleAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necessary cookies are essential and maintain information based on your activity on our site, like remembering your signed in account, selection of your language, or products added to the shopping cart. The website cannot work properly without these cookies. .
        /// </summary>
        public static string Rule_Necessary {
            get {
                return ResourceManager.GetString("Rule_Necessary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We use these cookies to measure, collect, analyse and report how users interact with our sites to better understand their behavior. Thanks to this, we can improve the site and provide better experience. The analytics service is provided by Smartlook..
        /// </summary>
        public static string Rule_Smartlook {
            get {
                return ResourceManager.GetString("Rule_Smartlook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Analytics.
        /// </summary>
        public static string RuleTitle_Analytics {
            get {
                return ResourceManager.GetString("RuleTitle_Analytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook Pixel.
        /// </summary>
        public static string RuleTitle_FacebookPixel {
            get {
                return ResourceManager.GetString("RuleTitle_FacebookPixel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Ads.
        /// </summary>
        public static string RuleTitle_GoogleAds {
            get {
                return ResourceManager.GetString("RuleTitle_GoogleAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necessary cookies.
        /// </summary>
        public static string RuleTitle_Necessary {
            get {
                return ResourceManager.GetString("RuleTitle_Necessary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smartlook.
        /// </summary>
        public static string RuleTitle_Smartlook {
            get {
                return ResourceManager.GetString("RuleTitle_Smartlook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information about cookies.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disallowed.
        /// </summary>
        public static string Toggle_False {
            get {
                return ResourceManager.GetString("Toggle_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed.
        /// </summary>
        public static string Toggle_True {
            get {
                return ResourceManager.GetString("Toggle_True", resourceCulture);
            }
        }
    }
}
